# Generated by Django 3.1.5 on 2021-02-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_donetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donetask',
            old_name='done_task',
            new_name='task',
        ),
    ]
